### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hadesmercy** [spiritwalking/ICPD-CD#1]
您好，想问一下您那个loverecord的学习路线是什么，如果想要做到类似的效果学习路线是什么呢？如果打扰到的话万分抱歉。

**Comment by spiritwalking** [comment]
> 您好，想问一下您那个loverecord的学习路线是什么，如果想要做到类似的效果学习路线是什么呢？如果打扰到的话万分抱歉。

你好，我是按顺序学习了html5，CSS3和JavaScript，但是其实并没有特别深入研究，烟花代码是使用的别人的开源代码，我只做了图片部件定位，背景图以及搭建网站等非常基础的工作。

如果只是想要有类似的效果，读下3种语言的文档就行，然后仿照代码自行制作；如果要深入研究建议参考教材或者是相应课程。

另祝朝朝暮暮，岁岁年年！

**Comment by hadesmercy** [comment]
感谢 🙏
祝 生活顺利 和和睦睦

发自我的iPhone
